# GitHub labels for AAP protocol repository
# Apply via: gh label create --repo thomaszta/aap-protocol (or import via UI)

- name: "spec"
  color: "1d76db"
  description: "Specification text or version"
- name: "documentation"
  color: "0075ca"
  description: "Docs, guides, examples"
- name: "protocol-proposal"
  color: "fbca04"
  description: "Proposed change to the protocol"
- name: "adoption"
  color: "0e8a16"
  description: "Adoption report or adopter"
- name: "bug"
  color: "d73a4a"
  description: "Something isn't correct"
- name: "question"
  color: "d876e3"
  description: "Question or discussion"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
