<<<<<<< HEAD
=======
# CI: Lint and validate AAP repo (markdown, links)
>>>>>>> 6b67a4cffcf7cc30e01f8845ccca823dedef6025
name: CI

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check.json'
          
      - name: Check for broken links in documentation
        run: |
          # Simple link checking for spec files
          find . -name "*.md" -type f | while read file; do
            echo "Checking $file"
            grep -o '\[.*\](.*)' "$file" || true
          done

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON examples
        run: |
          # Check for JSON files and validate them
          find . -name "*.json" -type f | while read file; do
            echo "Validating $file"
            python3 -m json.tool "$file" > /dev/null || exit 1
          done
          
      - name: Validate AAP address format in examples
        run: |
          # Check AAP address format in spec files
          grep -r "ai:[^~]+~[^#]+#[^ ]+" spec/ || true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build documentation site (placeholder)
        run: |
          echo "Documentation build would go here"
          echo "Future: Generate HTML from Markdown"
          
      - name: Check documentation completeness
        run: |
          # Check that all spec files have corresponding documentation
          echo "Checking documentation coverage..."
          ls spec/*.md | wc -l
          ls docs/*.md | wc -l

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [lint, validate, docs]
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
=======
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check markdown links (optional)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/markdown-link-check.json
          use-quiet-mode: "yes"
          use-verbose-mode: "no"
        continue-on-error: true

      - name: Check markdown lint (optional)
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
        continue-on-error: true

  validate:
    name: Validate structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check spec exists
        run: |
          test -f spec/aap-v0.02.md || (echo "Missing spec/aap-v0.02.md" && exit 1)
          echo "Spec OK"

      - name: Check README
        run: |
          test -f README.md && grep -q "Agent Address Protocol" README.md || exit 1
          echo "README OK"
>>>>>>> 6b67a4cffcf7cc30e01f8845ccca823dedef6025
